# Generated by Django 2.0.2 on 2018-02-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonaMascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_crianza', models.IntegerField()),
                ('mascota', models.ForeignKey(on_delete=True, to='mascotas.Mascotas')),
                ('persona', models.ForeignKey(on_delete=True, to='personas.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='mascotas',
            field=models.ManyToManyField(through='personas.PersonaMascotas', to='mascotas.Mascotas'),
        ),
    ]
